name: Code Quality

on:
  push:
    branches-ignore:
      - master

jobs:
  ESLint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        token: ${{ secrets.GitHub_PAT }}
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Restore CI Cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
    - name: Install Deps
      run: yarn
    - name: Lint code
      run: yarn lint

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v1
      with:
        token: ${{ secrets.GitHub_PAT }}
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Restore CI Cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
    - name: Install Deps
      run: yarn
    - name: Build Utils
      run: yarn ci:build --scope @rws-air/utils
    - name: Test
      run: yarn test
